### ISSUE TITLE
How to get each error in MultiErrorBuilder?

### ISSUE THREAD

**Issue by dionysius** [goph/emperror#37]
When using the [MultiErrorBuilder](https://github.com/goph/emperror/blob/master/multierr.go) and having multiple errors, I'm unable to get to each error. `(b *MultiErrorBuilder) ErrOrNil()` creates an object of the type `multiError` - which would allow me to use `(e *multiError) Errors()`, but is returned as type `error` (which is good). From outside, I'm unable to cast to this type, as it is not exported.

`_ = errs.ErrOrNil().(*emperror.multiError) // cannot refer to unexported name emperror.multiError`

**Comment by dionysius** [comment]
I could offer a PR, should I just make the MultiError exported or do you have other plans?

**Comment by sagikazarmark** [comment]
Thanks a lot for the PR, but ideally you should use a custom interface for this:

```go
// Errors returns a list of errors.
type Errors interface {
    Errors() []error
}
```

Then you can cast an error to this type.

I could imagine such interface added to this package though, so if you are willing to update your PR that would be nice.

**Comment by dionysius** [comment]
Updated PR, I suggest moving the conversation there
